---
title: "Text analysis in R"
output:
  html_notebook:
    fig_caption: yes
    number_sections: yes
    theme: journal
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---
# Element frequency analysis
```{r Element frequency, fig.height=10, fig.width=6, warning=FALSE}
#### Import alloy data ####
rm(list = ls())
library(dplyr)
alloy <- tbl_df(read.table("./Data/High-entropy alloy system - 工作表4.csv", 
                    header = TRUE, 
                    sep = ",",
                    colClasses = "character",
                    encoding = "UTF-8"))
#### Remove unexpected syntax ####
library(stringr)
N <- dim(alloy)[1]
for (i in 1:N){
  
  alloy[i, 1] <- str_replace_all(alloy[i, 1],
                                 "([A-Z])",
                                 "\\-\\1")
  alloy[i, 1] <- str_replace_all(alloy[i, 1],
                                 "[0-9|.|x|(|)]",
                                 "-")
  alloy[i, 1] <- str_replace_all(alloy[i, 1],
                                 "-+",
                                 " ")
}
alloy <- distinct(alloy) # Remove repeated observation
#### Tidy data & calculate element frequency ####
N <- dim(alloy)[1]
alloy <- mutate(alloy, line = 1:N)
library(tidytext)
library(wordcloud)
td_alloy <- alloy %>%
  unnest_tokens(element, Alloy, to_lower = FALSE)
td_alloy %>%
  count(element, sort = TRUE) %>%
  with(wordcloud(element, n, random.order = FALSE,
                 # random.color = TRUE,
                 colors = "red",
                 rot.per = 0,
                 ordered.colors = TRUE))

frequency <- td_alloy %>%
  count(element, sort = TRUE) %>%
  mutate(other = n / sum(n)) %>%
  ungroup()
periodic <- read.table("periodic-table.csv",
                       header = TRUE,
                       sep = ",") 
td_alloy$element <- factor(td_alloy$element, periodic$atomic_symbol)
frequency$element <- factor(frequency$element, periodic$atomic_symbol)
library(scales)
library(ggplot2)
ggplot(frequency, aes(x = element, y = other)) +
  geom_point() +
  geom_hline(yintercept = 0.025) +
  geom_vline(xintercept = 4.5) + 
  geom_vline(xintercept = 19.5) +
  geom_text(aes(label = element), check_overlap = TRUE, vjust = -1.0) +
  theme(legend.position="none") +
  labs(y = "Frequency", x = NULL)
```
# Clustering of HEAs system
```{r, warning=FALSE}
#### Group & Order td_alloy ####
td_alloy <- td_alloy %>%
  arrange(line, element) %>%
  group_by(line)
td_alloy$element <- as.character.factor(td_alloy$element)
#### Rename HEAs ####
for(i in 1:N) {
  temp <- filter(td_alloy, line == i)
  Alloy_newname <- temp[1, 2]
  for(j in 1:(dim(temp)[1]-1)) {
   Alloy_newname <- str_c(Alloy_newname, "-", temp[j+1, 2]) 
  }
  alloy[i, 1] <- Alloy_newname
  td_alloy$Alloy[td_alloy$line == i] <- Alloy_newname
}
alloy
td_alloy
#### Cluster HEAs ####
# library(cluster)
library(tm)
library(cluster)
print(dtm <- cast_dtm(td_alloy, Alloy, element, line))
# #K-means method
# HEAs_kmeans <- pam(dtm, 7)
# table(HEAs_kmeans$clustering)
#Hierarchical clustering
library(proxy)
d <- dist(as.matrix(dtm), method="cosine")
hc <- hclust(d, method="single")
library(ape)
plot(as.phylo(hc), type = "fan", tip.color = hsv(runif(15, 0.65, 
    0.95), 1, 1, 0.7), edge.color = hsv(runif(10, 0.65, 0.75), 1, 1, 0.7), edge.width = runif(20, 
    0.5, 3), use.edge.length = TRUE, col = "gray80")
# cl <- cutree(hc, 50)
# table(cl)
# findFreqTerms(dtm[cl==1], 50)
```

